WITH MILK AS (
    SELECT CART_ID,
        NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
), YOGURT AS (
    SELECT CART_ID,
        NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)
SELECT DISTINCT M.CART_ID
FROM MILK M
INNER JOIN YOGURT Y
    ON M.CART_ID = Y.CART_ID
ORDER BY 1;
