WITH TEMP AS
(SELECT USER_ID
FROM USER_INFO
WHERE SUBSTRING(JOINED,1,4) = '2021')

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT T1.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT T1.USER_ID) / (SELECT COUNT(USER_ID) FROM TEMP), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS T1
INNER JOIN TEMP AS T2
ON T1.USER_ID = T2.USER_ID
GROUP BY 1,2
ORDER BY 1, 2
;
